Opla/front

.babelrc, .travis.yml, package.json, tests/shared/components/IconExButton.test.js, tests/shared/components/__snapshots__/IconExButton.test.js.snap, yarn.lock
This PR adds everything we need to write tests with Jest.
=> Setup a test suite

package.json, src/public/index.html, yarn.lock
zoapp-front embeds both zrmc and zoapp-ui css.
=> Use zoapp-front css

package.json, src/shared/containers/botManager.jsx, src/shared/sagas/api.js, yarn.lock
=> Fix intent creation

package.json, src/plugins/fb-messenger/fbContainer.jsx, src/plugins/fb-messenger/fbSettings.jsx, src/shared/components/messagingsList.jsx, src/shared/containers/dialogs/publishDialog.jsx, yarn.lock
Fix #31
Fix #16
---
Diff is small because issues have been fixed on the upstream project (zrmc).
=> Fixes for publish dialog

src/plugins/app-connector/index.jsx
=> Rename native webapp to web page

src/shared/actions/api.js, src/shared/containers/explorerContainer.jsx, src/shared/reducers/app.js, src/shared/sagas/api.js, tests/shared/reducers/app.test.js
=> Fix intents list reordering

package.json, src/shared/containers/adminManager.jsx, src/shared/utils/timezones.js, yarn.lock
=> Allow to edit a bot details

package.json, src/shared/containers/createAssistant.jsx, tests/helpers.js, tests/setupTests.js, tests/shared/containers/__snapshots__/createAssistant.test.js.snap, tests/shared/containers/createAssistant.test.js, yarn.lock
[Issue 53](https://github.com/Opla/front/issues/53)
=> Implements errors visual display bot creation / signin

package.json, src/shared/containers/app.jsx, src/shared/reducers/app.js, src/shared/reducers/index.js, src/shared/reducers/message.js, tests/shared/reducers/app.test.js, tests/shared/reducers/index.test.js, tests/shared/reducers/message.test.js, yarn.lock
https://github.com/Zoapp/front/issues/39
=> extends Zoapp/front/appReducer

src/public/css/main.css, src/shared/containers/botManager.jsx
=> Fix wrong scrollbar display and positionning

src/shared/components/actionEditor.jsx, src/shared/components/actionsList.jsx, tests/shared/components/__snapshots__/actionEditor.test.js.snap, tests/shared/components/actionEditor.test.js
=> Bug specials characters into entity and variable chips

src/shared/containers/dashboard.jsx, tests/shared/containers/__snapshots__/dashboard.test.js.snap, tests/shared/containers/dashboard.test.js
links https://github.com/Opla/backend/issues/27
=> format error rate metric

src/shared/actions/api.js, src/shared/containers/dashboard.jsx, src/shared/sagas/api.js, tests/shared/containers/__snapshots__/dashboard.test.js.snap, tests/shared/containers/dashboard.test.js
links https://github.com/Opla/backend/issues/27
merge with https://github.com/Opla/backend/pull/33
=> add bot id to metrics request

src/shared/containers/createAssistant.jsx, tests/shared/containers/__snapshots__/createAssistant.test.js.snap, tests/shared/containers/createAssistant.test.js
deal with #53 
As see with @mikbry we display a general error message if the creation fail but we add some html5 validation form and I manage the language default selection.
=> enhance register form

src/shared/actions/app.js, src/shared/containers/createAssistant.jsx, tests/shared/containers/createAssistant.test.js
=> check if imported template is a valid JSON

package.json, src/server/index.js
=> make server/index.js compatile with node 8

src/shared/sagas/api.js
Fix #82 
but for me the real issue is more how url are build.
=> remove extra / in admin routes

tests/shared/components/__snapshots__/actionList.test.js.snap, tests/shared/components/actionList.test.js
Start the test creation of actionList
=> actionList component test

package.json, src/public/css/main.css, src/shared/containers/servicesContainer.jsx, yarn.lock
fix #73 
the deletion doesn't work for now, it looks like a backend issue
=> Admin extensions

src/shared/containers/createAssistant.jsx, tests/shared/containers/createAssistant.test.js
=> select empty template by default.

tests/shared/components/__snapshots__/tunnelBox.test.js.snap, tests/shared/components/tunnelBox.test.js
=> tunnelBox component tests

src/shared/components/actionsList.jsx, src/shared/components/tunnelBox.jsx, tests/shared/components/__snapshots__/actionList.test.js.snap, tests/shared/components/__snapshots__/tunnelBox.test.js.snap, tests/shared/components/donutChart.test.js, tests/shared/components/tunnelBox.test.js
=> Cleaning the "yarn test" command result

package.json, src/shared/store.js, yarn.lock
=> SignoutMiddleware integration

src/shared/components/actionsEditable.jsx, src/shared/components/actionsList.jsx, tests/shared/components/__snapshots__/actionList.test.js.snap
=> use correct Proptypes in actionEditable component

src/shared/containers/dashboard.jsx, tests/shared/containers/__snapshots__/dashboard.test.js.snap, tests/shared/containers/dashboard.test.js
Link to this issue : https://github.com/Opla/front/issues/75
=> Dashboard : display "No data" when no data available

src/public/css/main.css, src/shared/components/templatesList.jsx, src/shared/containers/createAssistant.jsx, src/shared/containers/home.jsx, tests/shared/components/__snapshots__/templatesList.test.js.snap, tests/shared/containers/__snapshots__/createAssistant.test.js.snap
Link to issue : https://github.com/Opla/front/issues/67 https://github.com/Opla/front/issues/94 https://github.com/Opla/front/issues/93
- Change display to be more in line with material design ✔️
- Use _main.css_ for component instead of file constants ✔️
- Change css rules for _fileInput_ class ✔️
- (Optionnal) Use image color to create a background color ✔️
=> Changes on components to solve issues

src/shared/containers/dashboard.jsx, tests/shared/containers/__snapshots__/dashboard.test.js.snap, tests/shared/containers/dashboard.test.js
fix #122 
fix #118 
---
#121 will be fixed by https://github.com/Opla/backend/pull/59
=> Fixes for Dashboard

src/shared/components/displayProviderEditor.jsx, src/shared/components/intentDetail.jsx, src/shared/containers/botManager.jsx, src/shared/containers/dialogs/ioDialog.jsx, src/shared/containers/dialogs/publishDialog.jsx, src/shared/containers/dialogs/serviceDialog.jsx, src/shared/containers/explorerContainer.jsx, src/shared/containers/intentContainer.jsx, src/shared/containers/sandboxContainer.jsx, src/shared/containers/servicesContainer.jsx
=> Fix buttons order

src/shared/actions/api.js, src/shared/actions/app.js, src/shared/containers/adminManager.jsx, src/shared/containers/botManager.jsx, src/shared/containers/createAssistant.jsx, src/shared/containers/dashboard.jsx, src/shared/sagas/api.js, tests/shared/reducers/app.test.js
This PR remove code duplicated from zoapp-front and uses the original code.
=> remove code duplicated from zoapp-front

package.json, src/shared/containers/home.jsx, yarn.lock
=> Wrong CSS Parameters

src/shared/containers/home.jsx
This PR is link to https://github.com/Opla/front/issues/130
=> Change on home.jsx

src/shared/sagas/api.js
=> Playground Websocket enhancement

package.json, src/public/css/main.css, src/public/css/messenger.css, src/shared/containers/intentContainer.jsx, yarn.lock
=> Update Zui and fix sub toolbar side effects

tests/shared/components/__snapshots__/intentDetail.test.js.snap, tests/shared/components/intentDetail.test.js
Start intentDetail test creation
=> intentDetail component test

src/shared/components/actionsEditable.jsx, src/shared/components/actionsList.jsx, tests/shared/components/actionsEditable.test.js
the component was still filled with the saved data.
=> reset actionsEditable once new one saved

src/shared/containers/intentContainer.jsx, tests/shared/containers/createAssistant.test.js, tests/shared/containers/intentContainer.test.js
=> Fix some toolbox display

src/shared/containers/drawerFooter.jsx
=> Display in new tab github and gitter

src/shared/components/messengerBox.jsx
=> Messenger message components

.gitignore, .travis.yml, Makefile, k8s/templates/0-configmap.yaml, k8s/templates/1-opla-front.yaml, k8s/templates/2-ingress.yaml, k8s/values.qa.yaml, k8s/values.yaml
- Hides secrets (keeps old ones for dev, and creates new ones for QA)
=> hide secrets & better templating

src/shared/opla.js
=> set documentation external link

webpack.common.js, webpack.dev.js
=> Fix node.env

package.json, src/shared/opla.js, yarn.lock
Update zoapp-front version
Made Zoapp responsable of loading application properties inside the store
=> Fix app reducer initialState

src/plugins/app-connector/appSettings.jsx, src/shared/containers/dialogs/serviceDialog.jsx
=> Fix webchat loading and display

src/shared/containers/dialogs/publishDialog.jsx
=> Published list platforms name + url

src/shared/components/actionsEditable.jsx, tests/shared/components/actionEditor.test.js, tests/shared/components/actionsEditable.test.js
=> Fix special char double encode

src/shared/components/actionsToolbox.jsx, tests/shared/components/__snapshots__/actionsToolbox.test.js.snap, tests/shared/components/actionsToolbox.test.js, tests/shared/containers/intentContainer.test.js
=> Display any button only for input

src/public/css/main.css
FIX https://github.com/Opla/community-edition/issues/26
FIX https://github.com/Opla/community-edition/issues/19
=> fix pointers

src/shared/containers/createAssistant.jsx
=> Fix error proptype

src/shared/components/actionsItem.jsx, src/shared/components/actionsList.jsx, src/shared/components/actionsToolbox.jsx, src/shared/components/conditionsActionsEditable.jsx, src/shared/components/intentDetail.jsx, src/shared/containers/intentContainer.jsx, tests/shared/components/__snapshots__/intentDetail.test.js.snap, tests/shared/components/actionsToolbox.test.js, tests/shared/containers/intentContainer.test.js
=> Add condition button

src/shared/components/messengerBox.jsx, tests/shared/components/messengerBox.test.js
close Opla/community-edition#38
=> fix messages order

package.json, src/shared/opla.js, yarn.lock
Use temporary drawer
need zoapp/front v0.23.1
close Opla/community-edition#10
=> change drawer type

src/shared/components/messengerBox.jsx, src/shared/containers/botManager.jsx
=> Fix error message

src/shared/components/messengerBox.jsx, tests/shared/components/messengerBox.test.js
close Opla/community-edition#37
=> Fix slash in messages

src/shared/containers/dialogs/ioDialog.jsx
See
https://github.com/Zoapp/react-materialcomponents/issues/122
=> remove ripple for Checkbox

src/public/css/messenger.css, src/shared/components/messengerBox.jsx, tests/shared/components/messengerBox.test.js
=> Enhancement playground msg ux

charts/opla-front/templates/2-ingress.yaml, myke.env, myke.yml
Allows access via http://<namespace>.<nginx_svc_load_balancer_ip>.xip.io/.
=> easy access

package.json, src/shared/components/actionsToolbox.jsx, src/shared/containers/sandboxContainer.jsx, tests/shared/components/__snapshots__/actionEditor.test.js.snap, tests/shared/components/__snapshots__/actionsToolbox.test.js.snap, yarn.lock
=> Add tooltips

src/shared/containers/botManager.jsx
FIX #252 
Also save intent when adding input
=> fill input and output when intent created

src/shared/components/actionsToolbox.jsx, tests/shared/components/__snapshots__/actionsToolbox.test.js.snap, tests/shared/components/actionsToolbox.test.js, tests/shared/containers/intentContainer.test.js
Mockup for 
#257 
#256 
#255 
#254
=> More actions

src/public/css/messenger.css, src/shared/components/actionsToolbox.jsx, src/shared/components/messengerBox.jsx, src/shared/containers/botManager.jsx, src/shared/containers/sandboxContainer.jsx, tests/shared/components/messengerBox.test.js
=> Messenger : tooltips and menu are now on top of messages

src/public/css/messenger.css, src/shared/components/messengerBox.jsx, src/shared/containers/sandboxContainer.jsx
=> Powered by, and move refresh in menu

src/shared/components/actionsEditable.jsx, tests/shared/components/__snapshots__/actionsList.test.js.snap, tests/shared/components/__snapshots__/intentDetail.test.js.snap
=> Fix cant add blocks in empty intent on Firefox

src/shared/components/actionsItem.jsx, src/shared/containers/intentContainer.jsx, tests/shared/components/__snapshots__/actionsList.test.js.snap, tests/shared/components/actionsItem.test.js, tests/shared/containers/intentContainer.test.js
=> Enhance intent new actions field

src/shared/components/actionsEditable.jsx, tests/shared/components/__snapshots__/actionEditor.test.js.snap, tests/shared/components/__snapshots__/actionsList.test.js.snap, tests/shared/components/__snapshots__/intentDetail.test.js.snap
=> Use flex for actionsEditable

Dockerfile, charts/opla-front/values.preprod.yaml, charts/opla-front/values.prod.yaml, charts/opla-front/values.qa.yaml, charts/opla-front/values.yaml, myke.yml
Make labels work properly, and be more descriptive :
=> instance-labels

src/shared/components/actionsList.jsx, src/shared/reducers/app/intents.js, src/shared/utils/actionsTools.js, tests/shared/utils/actionsTools.test.js
=> Check action validity
